[http]
  # Redirect to https
  [http.middlewares]
  [http.middlewares.httpsredirect.redirectScheme]
    scheme = https
    permanent = true
  # routers
  [http.routers]
  [http.routers.router_[domain1docker]_http]
     entrypoints = ['http']
     service = 'service-[domain1docker]'
     middlewares = ['httpsredirect']
     rule = 'host(`[domain1serverURL]`)'
   [http.routers.router_[domain1docker]_https]
     entrypoints = ['https','http']
     service = 'service-[domain1docker]'
     rule = 'host(`dev.domain1.xy`)'
     [http.routers.router_[domain1docker]_https.tls]
     certresolver = 'letsencrypt'
     [[http.routers.router_[domain1docker]_https.tls.domains]]
     main = '[domain1serverURL]'

  # Add the services
  [http.services]
    [http.services.service-domain1]
    [http.services.service-domain1.loadBalancer]
      [[http.services.service-domain1.loadBalancer.servers]]
      url = 'http://[domain1docker]'
